package game

import "core:fmt"
import "core:strings"
import "core:testing"

// Celestial names are presentation data derived from stable physical identity.
// Generating or rerolling them never advances the campaign RNG.
Celestial_Name_Style :: enum u8 {
	Any,
	Archival,
	Natural,
	Navigational,
	Settlement,
	Survey,
}

Planet_Name_Scheme :: enum u8 {
	Individual, // every world receives an independent proper name
	Systemic, // worlds share the system's naming tradition
	Orbital, // star name plus a conventional lower-case orbital letter
}

Celestial_Name_Config :: struct {
	style:          Celestial_Name_Style,
	planet_scheme:  Planet_Name_Scheme,
	max_length:     int,
	excluded_names: []string,
}

Catalog_Designation :: struct {
	prefix:    string,
	number:    u32,
	component: u8, // 0 is the primary star; planets begin with 'b'
}

Solar_System_Names :: struct {
	proper_name:         string,
	star_name:           string,
	star_names:          [MAX_SYSTEM_STARS]string,
	style:               Celestial_Name_Style,
	planet_scheme:       Planet_Name_Scheme,
	catalog:             Catalog_Designation,
	planet_names:        [MAX_SYSTEM_PLANETS]string,
	planet_designations: [MAX_SYSTEM_PLANETS]Catalog_Designation,
	planet_count:        int,
}

SYSTEM_NAMES_ARCHIVAL := [24]string {
	"Aster Record",
	"Bell Archive",
	"Cairn Ledger",
	"Cartographer's Rest",
	"Concordance",
	"Continuance",
	"Custodian",
	"First Register",
	"Glass Index",
	"Kepler Record",
	"Long Account",
	"Meridian Archive",
	"Old Measure",
	"Open Ledger",
	"Patient Record",
	"Pilgrim Index",
	"Quiet Testament",
	"Second Witness",
	"Surveyor's Mark",
	"The Almanac",
	"The Register",
	"True Account",
	"Vigil Record",
	"Witness Table",
}
SYSTEM_NAMES_NATURAL := [24]string {
	"Amber Current",
	"Ash Crown",
	"Blue Cedar",
	"Bracken",
	"Cloud Harbor",
	"Cold Orchard",
	"Copper Rain",
	"Dawn Reed",
	"Deepwater",
	"Foxglove",
	"Grey Heron",
	"Ilex",
	"Ironwood",
	"Juniper",
	"Kestrel",
	"Larkspur",
	"Mosslight",
	"Night Garden",
	"Pale River",
	"Red Willow",
	"Salt Meadow",
	"Stillwater",
	"Winter Elm",
	"Yellow Finch",
}
SYSTEM_NAMES_NAVIGATIONAL := [24]string {
	"Aft Bearing",
	"Arc Meridian",
	"Beacon Reach",
	"Blue Transit",
	"Crossing Point",
	"Far Meridian",
	"Final Bearing",
	"First Horizon",
	"Fixed Star",
	"Forward Mark",
	"Gateward",
	"High Traverse",
	"Keel North",
	"Lantern Reach",
	"Long Baseline",
	"Northing",
	"Outer Compass",
	"Passage End",
	"Port Meridian",
	"Signal Reach",
	"Still Bearing",
	"True Vector",
	"Waymark",
	"Westing",
}
SYSTEM_NAMES_SETTLEMENT := [24]string {
	"Common Ground",
	"Far Harbor",
	"First Shelter",
	"Good Earth",
	"Hearthward",
	"Home Reach",
	"Kindred Fields",
	"Labor's Rest",
	"Long Garden",
	"Mutual Harbor",
	"New Anchorage",
	"New Commons",
	"Open Hand",
	"Patient Harbor",
	"Rain Cistern",
	"Seedhouse",
	"Shared Acre",
	"Shelter Bay",
	"Stone Hearth",
	"The Allotment",
	"The Landing",
	"Warm Harbor",
	"Water Table",
	"Welcome Field",
}
SYSTEM_NAMES_SURVEY := [24]string {
	"Anomaly Seven",
	"Argent Signal",
	"Calibrant",
	"Distant Return",
	"Echo Station",
	"Faint Transit",
	"Field Reference",
	"Helix Source",
	"Long Baseline",
	"Low Signal",
	"Marker Nine",
	"Null Meridian",
	"Occultation",
	"Parallax",
	"Periapsis",
	"Reference Point",
	"Redshift",
	"Signal Twelve",
	"Spectral Line",
	"Transit Well",
	"Unresolved Source",
	"Variable One",
	"Vector Field",
	"Zenith Sample",
}

PLANET_NAMES_ARCHIVAL := [24]string {
	"Account",
	"Almanac",
	"Archive",
	"Bell",
	"Cairn",
	"Concordance",
	"Custodian",
	"Index",
	"Ledger",
	"Measure",
	"Memorandum",
	"Record",
	"Register",
	"Reliquary",
	"Second Witness",
	"Testament",
	"True Account",
	"Vigil",
	"Volume",
	"Witness",
	"Annex",
	"Catalogue",
	"Charter",
	"Codex",
}
PLANET_NAMES_NATURAL := [24]string {
	"Alder",
	"Arroyo",
	"Basin",
	"Birch",
	"Bracken",
	"Caldera",
	"Cedar",
	"Cinder",
	"Delta",
	"Elm",
	"Estuary",
	"Flint",
	"Heron",
	"Ilex",
	"Juniper",
	"Kestrel",
	"Marsh",
	"Moss",
	"Oak",
	"Rill",
	"Tarn",
	"Thicket",
	"Vale",
	"Yarrow",
}
PLANET_NAMES_NAVIGATIONAL := [24]string {
	"Aft Mark",
	"Bearing",
	"Compass",
	"Crossing",
	"Fathom",
	"Ford",
	"Gnomon",
	"Helm",
	"Horizon",
	"Keel",
	"Lantern",
	"Meridian",
	"Mooring",
	"Northing",
	"Plumb",
	"Reach",
	"Shoal",
	"Sounding",
	"Spindle",
	"Traverse",
	"Vector",
	"Waymark",
	"Westing",
	"Windlass",
}
PLANET_NAMES_SETTLEMENT := [24]string {
	"Allotment",
	"Anvil",
	"Cistern",
	"Commons",
	"Fallow",
	"Field",
	"Garden",
	"Harbor",
	"Hearth",
	"Landing",
	"Loom",
	"Orchard",
	"Pasture",
	"Quarry",
	"Rain",
	"Reed",
	"Salt",
	"Shelter",
	"Sill",
	"Stone",
	"Table",
	"Water",
	"Well",
	"Yard",
}
PLANET_NAMES_SURVEY := [24]string {
	"Calibrant",
	"Echo",
	"Glass",
	"Hollow",
	"Littoral",
	"Needle",
	"Occultation",
	"Parallax",
	"Periapsis",
	"Reference",
	"Redshift",
	"Return",
	"Sample",
	"Signal",
	"Spectral Line",
	"Threshold",
	"Transit",
	"Variable",
	"Vector Field",
	"Zenith",
	"Drift",
	"Helix",
	"Marker",
	"Sighting",
}

// Stars use short proper names. Keeping them separate from system/place names
// avoids odd constructions such as a star named "Rain Cistern".
STAR_NAMES := [64]string {
	"Adhara",
	"Alcor",
	"Alhena",
	"Alnair",
	"Ankaa",
	"Arcturus",
	"Ascella",
	"Atria",
	"Avior",
	"Bellatrix",
	"Canopus",
	"Capella",
	"Caph",
	"Castor",
	"Deneb",
	"Diphda",
	"Dubhe",
	"Electra",
	"Eltanin",
	"Enif",
	"Fomalhaut",
	"Hadar",
	"Hamal",
	"Izar",
	"Kaus",
	"Kochab",
	"Maia",
	"Markab",
	"Matar",
	"Menkent",
	"Merak",
	"Merope",
	"Mimosa",
	"Mintaka",
	"Mirach",
	"Mirfak",
	"Mizar",
	"Nashira",
	"Navi",
	"Nunki",
	"Peacock",
	"Phecda",
	"Polaris",
	"Pollux",
	"Procyon",
	"Rasalas",
	"Regulus",
	"Rigel",
	"Sabik",
	"Sadr",
	"Saiph",
	"Schedar",
	"Shaula",
	"Sirius",
	"Spica",
	"Suhail",
	"Tarazed",
	"Thuban",
	"Unukalhai",
	"Vega",
	"Vindemiatrix",
	"Wasat",
	"Wezen",
	"Zosma",
}

// Settlement names are complete authored literals because they can be stored
// directly in persistent campaign state. Generated compound names would be
// temporary-allocator strings and unsafe to retain.
SETTLEMENT_NAMES := [64]string {
	"Alder Anchorage",
	"Alder Commons",
	"Bell Cistern",
	"Bell Harbor",
	"Bracken Fields",
	"Bracken Refuge",
	"Cairn Hearth",
	"Cairn Station",
	"Cedar Garden",
	"Cedar Landing",
	"Concord Commons",
	"Concord Ward",
	"Copper Harbor",
	"Copper Yard",
	"Dawn Shelter",
	"Dawn Well",
	"Deepwater Anchorage",
	"Deepwater Reach",
	"Elm Commons",
	"Elm Fields",
	"Fallow Garden",
	"Fallow Hearth",
	"Glass Landing",
	"Glass Station",
	"Heron Harbor",
	"Heron Refuge",
	"Ilex Commons",
	"Ilex Ward",
	"Juniper Garden",
	"Juniper Well",
	"Kestrel Landing",
	"Kestrel Reach",
	"Lantern Anchorage",
	"Lantern Station",
	"Morrow Commons",
	"Morrow Harbor",
	"Moss Cistern",
	"Moss Shelter",
	"North Fields",
	"North Ward",
	"Orchard Commons",
	"Orchard Yard",
	"Pale Harbor",
	"Pale Refuge",
	"Rain Cistern",
	"Rain Garden",
	"Redwillow Hearth",
	"Redwillow Landing",
	"Salt Anchorage",
	"Salt Commons",
	"Stillwater Harbor",
	"Stillwater Well",
	"Stone Hearth",
	"Stone Yard",
	"Threshold Refuge",
	"Threshold Station",
	"Warm Harbor",
	"Warm Shelter",
	"West Commons",
	"West Reach",
	"Winter Garden",
	"Winter Ward",
	"Yarrow Fields",
	"Yarrow Landing",
}

GATE_ROOTS := [32]string {
	"Alder",
	"Ash",
	"Bell",
	"Blue",
	"Cairn",
	"Cold",
	"Copper",
	"Dawn",
	"Deep",
	"Far",
	"First",
	"Glass",
	"Grey",
	"Ilex",
	"Iron",
	"Keel",
	"Lantern",
	"Long",
	"Low",
	"Meridian",
	"North",
	"Outer",
	"Pale",
	"Pilgrim",
	"Red",
	"Salt",
	"Signal",
	"Still",
	"Tithe",
	"True",
	"Vigil",
	"West",
}
GATE_FORMS := [12]string {
	"Arch",
	"Crossing",
	"Door",
	"Gate",
	"Mark",
	"Mouth",
	"Passage",
	"Reach",
	"Threshold",
	"Transit",
	"Traverse",
	"Way",
}

DOOR_HASH_ADJECTIVES := [32]string {
	"amber",
	"ancient",
	"ashen",
	"brisk",
	"calm",
	"candid",
	"cold",
	"copper",
	"distant",
	"earnest",
	"faint",
	"gentle",
	"glass",
	"happy",
	"hollow",
	"iron",
	"kind",
	"lone",
	"long",
	"low",
	"muted",
	"open",
	"pale",
	"patient",
	"quiet",
	"red",
	"salt",
	"silver",
	"still",
	"true",
	"warm",
	"winter",
}
DOOR_HASH_ANIMALS := [32]string {
	"albatross",
	"antelope",
	"badger",
	"barracuda",
	"beetle",
	"caribou",
	"cormorant",
	"crane",
	"dormouse",
	"eel",
	"falcon",
	"fox",
	"gecko",
	"heron",
	"ibex",
	"kestrel",
	"lamprey",
	"marten",
	"moth",
	"narwhal",
	"octopus",
	"oriole",
	"otter",
	"petrel",
	"quail",
	"raven",
	"salmon",
	"tern",
	"urchin",
	"vole",
	"whale",
	"yak",
}
DOOR_HASH_OBJECTS := [32]string {
	"anchor",
	"bell",
	"bowl",
	"bridge",
	"bucket",
	"candle",
	"cistern",
	"compass",
	"cup",
	"door",
	"flask",
	"garden",
	"glass",
	"hammer",
	"harbor",
	"key",
	"lantern",
	"ledger",
	"loom",
	"needle",
	"orchard",
	"plumb",
	"quarry",
	"reel",
	"shelter",
	"spindle",
	"table",
	"teacup",
	"thimble",
	"vessel",
	"well",
	"windlass",
}

CATALOG_PREFIXES := [8]string{"LBH", "ARC", "HSP", "KIC", "MRS", "NSV", "PSR", "SRV"}


